name: 'Setup'
description: 'Sets up the project, installs dependencies, caches results'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version: 22.13
        registry-url: https://registry.npmjs.org
        always-auth: true
        cache: yarn
    - run: yarn install --frozen-lockfile
      shell: bash
