name: 'Setup'
description: 'Sets up the project, installs dependencies, caches results'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org
        always-auth: true
        cache: yarn
    - run: yarn install --frozen-lockfile
      shell: bash
