# This workflow checks if a PRs labels are valid after they've changed.
#
# It's executed separately from main.yaml because most PR interactions don't require checking labels,
# and also because coordinating validation to run after open-pr.yaml is tricky.
name: 'Validate labels when changing a PR'
on:
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  validate-labels:
    runs-on: ubuntu-latest
    concurrency: labels-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Validate that version bump labels are on the PR
        uses: ./.github/actions/validate-version-labels
        with:
          LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
